In [1]:
import pandas as pd


In [2]:
#loading the datasets
df_purchase = pd.read_csv("User_product_purchase_details_p2.csv")
df_user = pd.read_csv("user_demographics.csv")


In [3]:
#analyzing the datasets
df_purchase.head()

User_ID Product_ID City_Category Stay_In_Current_City_Years  \
0  1000001  P00069042             A                          2   
1  1000001  P00248942             A                          2   
2  1000001  P00087842             A                          2   
3  1000001  P00085442             A                          2   
4  1000002  P00285442             C                         4+   

   Marital_Status  Product_Category_1  Product_Category_2  Product_Category_3  \
0               0                   3                 NaN                 NaN   
1               0                   1                 6.0                14.0   
2               0                  12                 NaN                 NaN   
3               0                  12                14.0                 NaN   
4               0                   8                 NaN                 NaN   

   Purchase  
0      8370  
1     15200  
2      1422  
3      1057  
4      7969

In [4]:
df_purchase.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 9 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Product_ID                  550068 non-null  object 
 2   City_Category               550068 non-null  object 
 3   Stay_In_Current_City_Years  550068 non-null  object 
 4   Marital_Status              550068 non-null  int64  
 5   Product_Category_1          550068 non-null  int64  
 6   Product_Category_2          376430 non-null  float64
 7   Product_Category_3          166821 non-null  float64
 8   Purchase                    550068 non-null  int64  
dtypes: float64(2), int64(4), object(3)
memory usage: 37.8+ MB


In [5]:
df_purchase.describe()

User_ID  Marital_Status  Product_Category_1  Product_Category_2  \
count  5.500680e+05   550068.000000       550068.000000       376430.000000   
mean   1.003029e+06        0.409653            5.404270            9.842329   
std    1.727592e+03        0.491770            3.936211            5.086590   
min    1.000001e+06        0.000000            1.000000            2.000000   
25%    1.001516e+06        0.000000            1.000000            5.000000   
50%    1.003077e+06        0.000000            5.000000            9.000000   
75%    1.004478e+06        1.000000            8.000000           15.000000   
max    1.006040e+06        1.000000           20.000000           18.000000   

       Product_Category_3       Purchase  
count       166821.000000  550068.000000  
mean            12.668243    9263.968713  
std              4.125338    5023.065394  
min              3.000000      12.000000  
25%              9.000000    5823.000000  
50%             14.000000    8047.000000  
75%             16.000000   12054.000000  
max             18.000000   23961.000000

In [6]:
df_purchase.isnull().sum()

User_ID                            0
Product_ID                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [ ]:
df_purchase.shape


(550068, 9)

In [21]:
# as near about halve the data is missing in the 'Product_Category_2' and 'Product_Category_3' columns, we will drop these columns
df_purchase = df_purchase.drop(columns=['Product_Category_2','Product_Category_3'])

In [23]:
df_purchase.head()

User_ID Product_ID City_Category Stay_In_Current_City_Years  \
0  1000001  P00069042             A                          2   
1  1000001  P00248942             A                          2   
2  1000001  P00087842             A                          2   
3  1000001  P00085442             A                          2   
4  1000002  P00285442             C                         4+   

   Marital_Status  Product_Category_1  Purchase  
0               0                   3      8370  
1               0                   1     15200  
2               0                  12      1422  
3               0                  12      1057  
4               0                   8      7969

In [24]:
df_user.head()

User_ID Gender    Age  Occupation
0  1000001      F   0-17          10
1  1000002      M    55+          16
2  1000003      M  26-35          15
3  1000004      M  46-50           7
4  1000005      M  26-35          20

In [25]:
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5891 entries, 0 to 5890
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   User_ID     5891 non-null   int64 
 1   Gender      5891 non-null   object
 2   Age         5891 non-null   object
 3   Occupation  5891 non-null   int64 
dtypes: int64(2), object(2)
memory usage: 184.2+ KB


In [26]:
df_user.describe()

User_ID   Occupation
count  5.891000e+03  5891.000000
mean   1.003025e+06     8.153285
std    1.743379e+03     6.323140
min    1.000001e+06     0.000000
25%    1.001518e+06     3.000000
50%    1.003026e+06     7.000000
75%    1.004532e+06    14.000000
max    1.006040e+06    20.000000

In [27]:
df_user.isnull().sum()

User_ID       0
Gender        0
Age           0
Occupation    0
dtype: int64

In [28]:
df_purchase.columns

Index(['User_ID', 'Product_ID', 'City_Category', 'Stay_In_Current_City_Years',
       'Marital_Status', 'Product_Category_1', 'Purchase'],
      dtype='object')

In [29]:
df_user.columns

Index(['User_ID', 'Gender', 'Age', 'Occupation'], dtype='object')

In [30]:
# Merge on User_ID
df = pd.merge(df_purchase, df_user, on="User_ID", how="left")
# Create binary target
df["High_Value_Purchase"] = (df["Purchase"] >= 10000).astype(int)


In [31]:
df.head()

User_ID Product_ID City_Category Stay_In_Current_City_Years  \
0  1000001  P00069042             A                          2   
1  1000001  P00248942             A                          2   
2  1000001  P00087842             A                          2   
3  1000001  P00085442             A                          2   
4  1000002  P00285442             C                         4+   

   Marital_Status  Product_Category_1  Purchase Gender   Age  Occupation  \
0               0                   3      8370      F  0-17          10   
1               0                   1     15200      F  0-17          10   
2               0                  12      1422      F  0-17          10   
3               0                  12      1057      F  0-17          10   
4               0                   8      7969      M   55+          16   

   High_Value_Purchase  
0                    0  
1                    1  
2                    0  
3                    0  
4                    0

In [32]:
df["Stay_In_Current_City_Years"].unique()

array(['2', '4+', '3', '1', '0'], dtype=object)

In [33]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
one_hot_encoder = OneHotEncoder(sparse_output=False)
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
df['City_Category'] = label_encoder.fit_transform(df['City_Category'])
df['Stay_In_Current_City_Years'] = label_encoder.fit_transform(df['Stay_In_Current_City_Years'])
df['Age'] = label_encoder.fit_transform(df['Age'])


In [34]:
df.head()

User_ID Product_ID  City_Category  Stay_In_Current_City_Years  \
0  1000001  P00069042              0                           2   
1  1000001  P00248942              0                           2   
2  1000001  P00087842              0                           2   
3  1000001  P00085442              0                           2   
4  1000002  P00285442              2                           4   

   Marital_Status  Product_Category_1  Purchase  Gender  Age  Occupation  \
0               0                   3      8370       0    0          10   
1               0                   1     15200       0    0          10   
2               0                  12      1422       0    0          10   
3               0                  12      1057       0    0          10   
4               0                   8      7969       1    6          16   

   High_Value_Purchase  
0                    0  
1                    1  
2                    0  
3                    0  
4                    0

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# Drop columns not needed
df = df.drop(["Product_ID"], axis=1)
# dummy for categorical
# Replace missing
df = df.fillna(0)
X = df.drop(["High_Value_Purchase", "Purchase"], axis=1)
y = df["High_Value_Purchase"]

In [36]:
df.head()

User_ID  City_Category  Stay_In_Current_City_Years  Marital_Status  \
0  1000001              0                           2               0   
1  1000001              0                           2               0   
2  1000001              0                           2               0   
3  1000001              0                           2               0   
4  1000002              2                           4               0   

   Product_Category_1  Purchase  Gender  Age  Occupation  High_Value_Purchase  
0                   3      8370       0    0          10                    0  
1                   1     15200       0    0          10                    1  
2                  12      1422       0    0          10                    0  
3                  12      1057       0    0          10                    0  
4                   8      7969       1    6          16                    0

In [37]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)

c:\Users\User\Desktop\FastAPiprjs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [39]:
y_pred_lr= model.predict(x_test)

In [46]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix,precision_score,recall_score,f1_score
print("Metrics for Logistic regression")

print("Precision Score:", precision_score(y_test, y_pred_lr))
print("Recall Score:", recall_score(y_test, y_pred_lr))
print("F1 Score:", f1_score(y_test, y_pred_lr))

Metrics for Logistic regression
Precision Score: 0.7833312546769768
Recall Score: 0.6668524712002973
F1 Score: 0.7204140739253864


In [44]:
print("Confusion matrix for Logistic Regression:")
print(confusion_matrix(y_test, y_pred_lr))

Confusion matrix for Logistic Regression:
[[65391  6949]
 [12551 25123]]


In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [59]:
x_train.shape

(440054, 8)

In [76]:
import numpy as np
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.layers import Dropout
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.metrics import Precision, Recall, BinaryAccuracy

# prepare features: drop identifier and scale (reuse StandardScaler imported earlier)
x_train = x_train.drop("User_ID", axis=1)
x_test = x_test.drop("User_ID", axis=1)

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# handle class imbalance
classes = np.unique(y_train)
cw = compute_class_weight(class_weight="balanced", classes=classes, y=y_train)
class_weight = {int(c): float(w) for c, w in zip(classes, cw)}


model = Sequential([
    Dense(64, activation="relu", input_shape=(x_train.shape[1],)),
    Dense(32, activation="relu"),
    Dropout(0.2),
    Dense(16, activation="relu"),
    Dense(1, activation="sigmoid")
])

model.compile(optimizer="adam",
              loss="binary_crossentropy",
              metrics=[Precision(), Recall(), BinaryAccuracy()])

es = EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True)

model.fit(x_train, y_train, epochs=20, batch_size=1024, validation_split=0.2,
          class_weight=class_weight, callbacks=[es])


Epoch 1/20


c:\Users\User\Desktop\FastAPiprjs\venv\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


344/344 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - binary_accuracy: 0.8160 - loss: 0.4881 - precision_3: 0.7244 - recall_1: 0.7534 - val_binary_accuracy: 0.8367 - val_loss: 0.4410 - val_precision_3: 0.7435 - val_recall_1: 0.8046
Epoch 2/20
344/344 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.8338 - loss: 0.4329 - precision_3: 0.7429 - recall_1: 0.7927 - val_binary_accuracy: 0.8389 - val_loss: 0.3940 - val_precision_3: 0.7435 - val_recall_1: 0.8145
Epoch 3/20
344/344 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.8540 - loss: 0.3608 - precision_3: 0.7520 - recall_1: 0.8609 - val_binary_accuracy: 0.8757 - val_loss: 0.3287 - val_precision_3: 0.7601 - val_recall_1: 0.9350
Epoch 4/20
344/344 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.8712 - loss: 0.3270 - precision_3: 0.7564 - recall_1: 0.9246 - val_binary_accuracy: 0.8763 - val_loss: 0.3123 - val_precision_3: 0.7615 - val_recall_1: 0.9345
Epoch 5/20
344/344 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.8747 - los

In [81]:
y_pred_nn = model.predict(x_test)

3438/3438 ━━━━━━━━━━━━━━━━━━━━ 2s 431us/step


In [82]:
y_pred_nn

array([[0.9037606 ],
       [0.85923654],
       [0.09310613],
       ...,
       [0.10314687],
       [0.01968235],
       [0.7231072 ]], shape=(110014, 1), dtype=float32)

In [84]:
y_pred_nn= (y_pred_nn > 0.5).astype(int)

In [85]:
y_pred_nn

array([[1],
       [1],
       [0],
       ...,
       [0],
       [0],
       [1]], shape=(110014, 1))

In [86]:
print("Metrics for MLP Neural Network")

print("Precision Score:", precision_score(y_test, y_pred_nn))
print("Recall Score:", recall_score(y_test, y_pred_nn))
print("F1 Score:", f1_score(y_test, y_pred_nn))

Metrics for MLP Neural Network
Precision Score: 0.7818693792019559
Recall Score: 0.9507617985878856
F1 Score: 0.8580839901300817


In [87]:
print("confusion_matrix for MLP Neural Network:")
print(confusion_matrix(y_test, y_pred_nn))

confusion_matrix for MLP Neural Network:
[[62347  9993]
 [ 1855 35819]]
